### ISSUE TITLE
dog fails when more dogfiles are present in subdirectories

### ISSUE THREAD

**Issue by n-marshall** [dogtools/dog#110]

**Comment by slapresta** [comment]
What kind of failure happens?

**Comment by n-marshall** [comment]
I was going to post details about this, but now i'm completely unable to reproduce the error...

Here's the error log:

```
NicolasMarshalls-MBook-Air% dog build-vegeta
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x13a658c16630 pc=0x113bb]

runtime stack:
runtime.throw(0x20d0c0, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x2c1120)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x2c1120, 0x4, 0x42, 0x316ef0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff208)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x2c1120, 0x4, 0x10000000042, 0x1105f)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x2c40d0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x2c40d0, 0x316ef0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x311000, 0x42, 0x316ef0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x2be200)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:245 fp=0xc820097788 sp=0xc820097780
runtime.mallocgc(0x8000, 0x162bc0, 0x1, 0xc8200e4800)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc820097860 sp=0xc820097788
runtime.newarray(0x162bc0, 0x2000, 0xc8200e4800)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc8200978a0 sp=0xc820097860
runtime.makeslice(0x15a200, 0x6, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/slice.go:32 +0x165 fp=0xc8200978f0 sp=0xc8200978a0
regexp.(*bitState).reset(0xc8200dd960, 0xc, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/regexp/backtrack.go:87 +0x101 fp=0xc820097970 sp=0xc8200978f0
regexp.(*machine).backtrack(0xc8200de7e0, 0x365308, 0xc8200de8b8, 0x0, 0xc, 0x0, 0x1)
	/usr/local/Cellar/go/1.6.2/libexec/src/regexp/backtrack.go:324 +0x106 fp=0xc8200979e8 sp=0xc820097970
regexp.(*Regexp).doExecute(0xc8200fe000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820013382, 0xc, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/regexp/exec.go:449 +0x423 fp=0xc820097b48 sp=0xc8200979e8
regexp.(*Regexp).MatchString(0xc8200fe000, 0xc820013382, 0xc, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/regexp/regexp.go:411 +0x67 fp=0xc820097bb8 sp=0xc820097b48
regexp.MatchString(0x1d8040, 0xf, 0xc820013382, 0xc, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/regexp/regexp.go:438 +0x83 fp=0xc820097be8 sp=0xc820097bb8
github.com/dogtools/dog/parser.LoadDogFile(0xc820016720, 0x0, 0x0)
	/Users/nicolasmarshall/dev/go/src/github.com/dogtools/dog/parser/parser.go:102 +0x17b fp=0xc820097cc0 sp=0xc820097be8
main.main()
	/Users/nicolasmarshall/dev/go/src/github.com/dogtools/dog/main.go:57 +0x7be fp=0xc820097f40 sp=0xc820097cc0
runtime.main()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820097f90 sp=0xc820097f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820097f98 sp=0xc820097f90
```

Now just after that I renamed two Dogfiles.yml in two subdirectories, ran the same command again, and

```
NicolasMarshalls-MBook-Air% dog build-vegeta
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```

It didn't do anything useful this time, but at least it didn't fail like the first time.

Now, several changes in the Dogfile later, I can rename my two subdirectory files to Dogfile.yml again, and I can't get the error to happen again. I'm thinking this might have nothing to do with Dogfiles in subdirectories...

**Comment by xsb** [comment]
@n-marshall Thanks for opening the issue and sorry for replying so late. I'm not sure I'm following but understand that you can't reproduce the error, right?
